export const USER_LOGIN = `USER/LOGIN`;
export const USER_LOGOUT = `USER/LOGOUT`;

export const TEAMS_ADD_TEAM = `TEAMS/ADD_TEAM`;
export const TEAMS_ADD_TEAMS = `TEAMS/ADD_TEAMS`;
export const TEAMS_SELECT_TEAM = `TEAMS/SELECT_TEAM`;
export const TEAMS_SELECT_WINDOW = `TEAMS/SELECT_WINDOW`;
export const TEAMS_SET_TASKS = `TEAMS/SET_TASKS`;
export const TEAMS_ADD_TASK = `TEAMS/ADD_TASK`;
export const TEAMS_ADD_MEMBER = `TEAMS/ADD_MEMBER`;
export const TEAMS_SET_ACTIVE_TASK = `TEAMS/SET_ACTIVE_TASK`;

export const APP_SET_WINDOW = `APP/SET_WINDOW`;
